name: Code linter

on:
  push:
    branches:
      - odmantic
  pull_request:
    branches:
      - odmantic

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Run isort
        run: poetry run isort .
      - name: Run black
        run: poetry run black .
